### ISSUE TITLE
Slack workflow builder would not accept . [dot] in a variable name

### ISSUE THREAD

**Issue by shemtovo** [stevengill/pancake-studio#9]
When trying to insert a key with a dot into Slack workflow builder it gives an error saying "Key must only contain a combination of letters, numbers, hyphens, and underscores"

**Comment by amarinelli** [comment]
This should be fixed by #10 so we can close this out. Since the new Workflow Builder does not supports `.` notation in variables names, the service was updated to use `_`. Dots still supported for legacy WFB to maintain compatibility.
